// Generated by gencpp from file ur5_notebook/blocks_info.msg
// DO NOT EDIT!


#ifndef UR5_NOTEBOOK_MESSAGE_BLOCKS_INFO_H
#define UR5_NOTEBOOK_MESSAGE_BLOCKS_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ur5_notebook
{
template <class ContainerAllocator>
struct blocks_info_
{
  typedef blocks_info_<ContainerAllocator> Type;

  blocks_info_()
    : name()
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  blocks_info_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::ur5_notebook::blocks_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur5_notebook::blocks_info_<ContainerAllocator> const> ConstPtr;

}; // struct blocks_info_

typedef ::ur5_notebook::blocks_info_<std::allocator<void> > blocks_info;

typedef boost::shared_ptr< ::ur5_notebook::blocks_info > blocks_infoPtr;
typedef boost::shared_ptr< ::ur5_notebook::blocks_info const> blocks_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur5_notebook::blocks_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur5_notebook::blocks_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ur5_notebook::blocks_info_<ContainerAllocator1> & lhs, const ::ur5_notebook::blocks_info_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ur5_notebook::blocks_info_<ContainerAllocator1> & lhs, const ::ur5_notebook::blocks_info_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ur5_notebook

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ur5_notebook::blocks_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur5_notebook::blocks_info_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur5_notebook::blocks_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur5_notebook::blocks_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur5_notebook::blocks_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur5_notebook::blocks_info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur5_notebook::blocks_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2edff07075d48378c13052415416989c";
  }

  static const char* value(const ::ur5_notebook::blocks_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2edff07075d48378ULL;
  static const uint64_t static_value2 = 0xc13052415416989cULL;
};

template<class ContainerAllocator>
struct DataType< ::ur5_notebook::blocks_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur5_notebook/blocks_info";
  }

  static const char* value(const ::ur5_notebook::blocks_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur5_notebook::blocks_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"float64 x  # x size in the world\n"
"float64 y  # y size in the world\n"
"float64 z  # z size in the world\n"
"\n"
;
  }

  static const char* value(const ::ur5_notebook::blocks_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur5_notebook::blocks_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct blocks_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur5_notebook::blocks_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur5_notebook::blocks_info_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR5_NOTEBOOK_MESSAGE_BLOCKS_INFO_H
